from pydantic import BaseModel, Field
from typing import Any, Dict, Optional
from datetime import datetime

class SystemEvent(BaseModel):
    """
    Represents an internal system event (e.g., 'service_started', 'error_occurred').
    """
    type: str = Field(..., description="Event type identifier")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Event data")
    timestamp: float = Field(default_factory=lambda: datetime.now().timestamp(), description="Unix timestamp of the event")
    source: str = Field(..., description="Service that generated the event")

class Signal(BaseModel):
    """
    Represents a trading signal generated by the Strategy Engine.
    """
    timestamp: float = Field(..., description="Unix timestamp of the signal")
    asset: str = Field(..., description="Asset symbol")
    action: str = Field(..., description="Action to take (e.g., 'BUY', 'SELL')")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score (0.0 - 1.0)")
    strategy_id: str = Field(..., description="Identifier of the strategy that generated the signal")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional signal details")
